if(WIN32)
    set(Geode_DIR "C:/Users/runneradmin/AppData/Local/Geode/sdk")
    set(ENV{GEODE_SDK} "C:/Users/runneradmin/AppData/Local/Geode/sdk")
else()
    set(Geode_DIR "/home/runner/.local/share/Geode/sdk")
    set(ENV{GEODE_SDK} "/home/runner/.local/share/Geode/sdk")
endif()

list(APPEND CMAKE_PREFIX_PATH "${Geode_DIR}")

if(EXISTS "${Geode_DIR}/cmake/GeodeConfig.cmake")
    include("${Geode_DIR}/cmake/GeodeConfig.cmake")
else()
    include("${Geode_DIR}/share/Geode/cmake/GeodeConfig.cmake")
endif()
