name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            target: Win32
          - os: ubuntu-latest
            target: Android32

    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Geode CLI
        uses: geode-sdk/cli/.github/actions/setup@main

      - name: Configure and Build Mod
        run: |
          geode sdk install v5.8.2
          cmake -B build -A ${{ matrix.config.target == 'Win32' && 'Win32' || '' }} -DGeode_DIR="${{ github.workspace }}/geode-sdk"
          cmake --build build --config Release
          
