name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            platform: win
            sdk_path: C:/Users/runneradmin/AppData/Local/Geode/sdk
          - os: ubuntu-latest
            platform: android
            sdk_path: /home/runner/.local/share/Geode/sdk

    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          platform: ${{ matrix.config.platform }}
          sdk: v5.8.2
        env:
          GEODE_SDK: ${{ matrix.config.sdk_path }}
          Geode_DIR: ${{ matrix.config.sdk_path }}
          
